# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: null
        cookie_secure: true
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 3600 # 1 ساعت
        cookie_samesite: none # برای CORS باید Lax یا None باشه
        save_path: '%kernel.project_dir%/var/sessions'
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 100

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
