# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: [ '*' ] # اجازه به همه دامنه‌ها
        allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ '*' ] # اجازه به همه هدرها
        expose_headers: [ 'Link' ]
        allow_credentials: true # اجازه ارسال کوکی‌ها
        max_age: 3600
    paths:
        '^/':
            # اعمال تنظیمات به همه مسیرها
            allow_origin: [ '*' ]
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
            allow_headers: [ '*' ]
            expose_headers: [ 'Link' ]
            allow_credentials: true
            max_age: 3600
